### PR TITLE
Add Sonar CI-based analysis

### LINKED ISSUE #52: Add Sonar CI-based analysis
Create the necessary Github Action and add the required property to the pom.xml

### PR DESCRIPTION
**Pull request by andrasig-bme**
Added the necessary pom properties and Github Action .yml for CI-based Sonar analysis.

Fixes #52

### CODE REVIEW

**Review by forriM — APPROVED** [review]
looks good

**Review by naslevente — APPROVED** [review]
Perfect!

**Review by FanniFarkas — APPROVED** [review]
Nice job!

**Comment by andrasig-bme** [comment]
#52

**Pull request merged**
